import time
from playwright.sync_api import sync_playwright, Page, expect

def verify_tool_chaining(page: Page):
    """
    This test verifies that the new ToolCallManager correctly handles a simple tool call.
    It checks for the sequential message chain: assistant (with tool_call) -> tool (with response).
    """
    # 1. Arrange: Go to the chat application homepage.
    # The file server is running on port 8000.
    page.goto("http://127.0.0.1:8000")

    # 2. Act: Find the message input, type a prompt that will trigger a tool call, and send it.
    message_input = page.locator("#message-input")
    expect(message_input).to_be_visible()

    # Use a prompt that will reliably trigger the get_current_datetime tool.
    message_input.fill("What is the current date and time?")

    # Click the send button.
    send_button = page.get_by_role("button", name="Send")
    send_button.click()

    # 3. Assert: Wait for the new message chain to appear.
    # We expect to see three messages in total: User, Assistant (tool call), Tool (response).

    # Wait for the assistant's message containing the tool call.
    # We can identify it by looking for the tool_call_id attribute generated by our new manager.
    assistant_message_locator = page.locator('.message-content:has-text("dma:tool_call")')
    expect(assistant_message_locator).to_be_visible(timeout=15000) # Increased timeout for model response

    # Verify the tool_call_id is present, confirming our ID injection works.
    expect(assistant_message_locator.locator('[tool_call_id]')).to_have_attribute('tool_call_id', timeout=5000)

    # Now, wait for the subsequent tool response message.
    # This message should have the role 'tool' and contain the date.
    # We look for a message with the 'role-tool' class.
    tool_response_locator = page.locator(".message.role-tool")
    expect(tool_response_locator).to_be_visible(timeout=10000)

    # The content of the tool response should contain a date/time string (e.g., "202")
    expect(tool_response_locator.locator(".message-content")).to_contain_text('"202', timeout=5000)

    # 4. Screenshot: Capture the final state of the chat for visual verification.
    chat_container = page.locator("#chat-container")
    chat_container.screenshot(path="jules-scratch/verification/tool_chain_verification.png")

def main():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        try:
            verify_tool_chaining(page)
            print("Verification script completed successfully.")
        except Exception as e:
            print(f"Verification script failed: {e}")
            # Save a screenshot on failure for debugging
            page.screenshot(path="jules-scratch/verification/failure_screenshot.png")
        finally:
            browser.close()

if __name__ == "__main__":
    main()